### ISSUE TITLE
Image Size Incorrect

### ISSUE THREAD

**Issue by Exosq** [wynick27/steam-missing-covers-downloader#4]
After entering steam credentials, when trying to download covers, message error "Image size incorrect" is shown.

**Comment by wynick27** [comment]
That's because steamgriddb.com exists before steam UI update. And many covers uploaded there are not 600x900. Their api doesn't support filtering image size yet. So currently the script has to download the images first  and check for the image size, if it's not 600x900 then it'll show this message and try to download another cover.

**Comment by Exosq** [comment]
Ok, so is it normal that it doesn't download anything even if i have 50 games missing covers ?

**Comment by wynick27** [comment]
That's possible since there are 28,000 games that don't have correct cover and steamgriddb only has a few of them. As long as there are no error message it should be fine.

**Comment by Exosq** [comment]
Ok, thank you for responding and thank you for your work.

**Comment by wynick27** [comment]
I've found the source of problem. The SGDB api now won't return any new 600x900 arts for backward compatibility. It previously did so because of a bug.
